### PR TITLE
Use donfig for handling posttroll environment variables

### PR DESCRIPTION
**Pull request by mraspaud**
This PR makes use of donfig to handle posttroll configuration

### CODE REVIEW

**Comment by pnuu** [comment]
We also have `NAMESERVER_PORT` and `DEBUG` environment variables. But I guess Donfig only handle variables that are prefixed?

**Review by pnuu — APPROVED** [review]
Oh, and otherwise LGTM

**Comment by pnuu** [comment]
It seems that the new environment variable handling isn't working for defining the min/max port range :thinking:

**Comment by mraspaud** [comment]
> We also have `NAMESERVER_PORT` and `DEBUG` environment variables. But I guess Donfig only handle variables that are prefixed?

Yes indeed. So that would need a longer process of deprecation.

**Review by djhoese — APPROVED** [review]

**Pull request merged**
