### PR TITLE
Add Python 3 support

### PR DESCRIPTION
**Pull request by pnuu**
This PR adds Python 3 support to posttroll. Some of the changes were taken from branch feature-python3, but this is based on the current develop branch.

### CODE REVIEW

**Comment by pnuu** [comment]
With Python 3 (both 3.4 and 3.6) the unittests give warnings about unclosed sockets, eg. here: https://travis-ci.org/pytroll/posttroll/jobs/402971118#L489

**Comment by pnuu** [comment]
Tests pass for 2.7, 3.5 and 3.6 in Travis. For 3.4 there's a failure in the number of subscribed addresses (2, should be 1). I seem to get similar situation on my test server using 2.7 and 3.6 (conda) with as many as 60 addresses. This might be coming from the fact that the same network has also operational services and many additional connections are created to them. This shouldn't be the case with Travis, so I'm mystified.

@mraspaud any ideas?

Real usage tests still to be performed, but at least nameserver starts and seems to work.

**Comment by djhoese** [comment]
You could maybe go as far as testing 3.6 and 3.7 and dropping 3.5 from the tests. I'm going to have to do the same for some of the other libraries.

**Comment by pnuu** [comment]
Tested actual usage on 2.7 and 3.6, at least nameserver and message sending works. Also trollflow running on 2.7 is able to process the incoming messages from 2.7/3.6.

**Comment by pnuu** [comment]
I added 3.5 when I noticed that it's the default Python 3 version in Ubuntu 16.04 LTS. No big feelings about having it tested, tho. I'll add 3.7.

**Comment by pnuu** [comment]
I can't figure out why Python 3.5 and 3.6 get two subscribed addresses in `test_pubsub.py`. @mraspaud could you take a look?

**Pull request merged**
