### PR TITLE
broadcast_port and defautl_publish_port can be read from a config file

### PR DESCRIPTION
**Pull request by loreclem**
broadcast_port and defautl_publish_port can be read from a config file called postroll.ini located in the $PPP_CONFIG_DIR (there's an example in the new example directory under doc). If the file is not present, the default are taken (hardcoded in the code).

### CODE REVIEW

**Comment by mraspaud** [comment]
What happens if the file is not present ?

**Comment by loreclem** [comment]
It will just use the default values, as before (hardcoded)

**Comment by loreclem** [comment]
Or well, I to be honest I should check.. I use an "or" form and I'm not 100% sure it works even if the file is missing

**Comment by loreclem** [comment]
Martin, after the two previous commits it should now be better.
Unit tests with a config file provided, passed.
Unit tests withouth config file (default situation): 4 out of 16 fail. As far as I understand, this is due to the fact that there are many users on that server that run several instances of trollduction, which causes addresses collisions. But I am not 100% sure.

**Comment by pnuu** [comment]
I changed the base from master to develop, so rebase might be needed.

**Comment by pnuu** [comment]
Is this PR still valid or should it be closed?
Develop branch will be deleted, so changed the base branch back to `master`.

**Pull request closed without merging**
